# Fuente única: preguntas -> HTML + encabezados del Sheet.
# t: s=texto corto, l=párrafo, r=opción única, c=casillas, n=escala 1-10, e=email gmail, p=teléfono, a=número
Q = [
 (1,"Nombre completo","s","Tu nombre completo",""),
 (2,"Sexo","r","Eres hombre o mujer?","",["Hombre","Mujer","Otros"]),
 (3,"Instagram","s","Cual es tu usuario en Instagram?","Si no tienes, contesta NO TENGO."),
 (4,"Correo Gmail","e","Escribe tu correo Gmail - Lo usaremos para las plataforma de clase y planificación.","Debe ser correo de google Gmail."),
 (5,"WhatsApp","p","Escribe tu número de teléfono - Whatsapp.",""),
 (6,"Edad","a","Tu Edad?",""),
 (7,"País y ciudad","s","De dónde eres? - Pais y ciudad",""),
 (8,"Profesión o emprendimiento","l","A qué te dedicas? especifica a detalle tu profesión o emprendimiento.",""),
 (9,"Situación laboral","l","Cómo te sientes respecto a tu trabajo? - Situación laboral",'Sé específico, por ejemplo, no digas "Me siento bien" sino "Me siento exitoso por llegar a este nivel profesional y emocionado por proyectarme a futuro"'),
 (10,"Hobbies","l","Qué hobbies tienes? Qué te gusta hacer fuera del trabajo?",""),
 (11,"Redes sociales","l","Qué redes sociales acostumbras a usar? - Escribe todas las que uses y cuales tiendes a usar más.",""),
 (12,"Familia cercana","l","¿Cuántos integrantes son en tu familia cercana?","Nombra si tienes pareja, padres, hijos, hermanos, etc."),
 (13,"Estado físico actual","l","Cómo te sientes con tu estado físico actual?",'Describe tus emociones y situación al respecto, por ejemplo, no respondas "ME SIENTO MAL", responde "No me siento a gusto cuando la ropa no me queda bien"'),
 (14,"Descripción del cuerpo","l","Cómo describirías tu cuerpo actualmente?","Alguna característica o forma de denominarlo, por ejemplo: fofo, delgado con grasa, grande, en sobrepeso, obeso, etc."),
 (15,"Tiempo con el problema","s","Cuánto tiempo llevas con este problema?",""),
 (16,"Problemas en el proceso","l","Qué problemas has tenido en tu proceso y tu cuerpo?",'Lista todos los que puedas. Sé todo lo específico que puedas, cuanto más escribas más ayudará. Por ejemplo no pongas "no ser constante" pon: "He probado hacer dietas pero he pasado mucha hambre y no disfruto, por lo que lo termino dejando y vuelvo a subir de peso…"'),
 (17,"Qué necesita para resolverlo","l","¿Qué crees que necesitas para resolver este problema o problemas?",""),
 (18,"Intentos que no funcionaron","l","¿Qué has intentado en el pasado que NO te ha funcionado?","Especifica a detalle."),
 (19,"Preocupaciones","l","¿Qué te mantiene despierto por las noches? - Preocupaciones",""),
 (20,"Miedos físicos y mentales","l","A qué le tienes miedo en el ámbito de tu estado físico y mental? - Miedos",""),
 (21,"Enojos","l","Sobre qué estás enojado en el ámbito de tu estado físico y mental? ¿Con quién?","Por ejemplo, falsas promesas o productos que te hacen perder dinero, etc."),
 (22,"Top 3 frustraciones","l","Cuáles son tus top 3 frustraciones de tu estado físico y mental?",""),
 (23,"Malos hábitos","l","Cuáles son tus malos hábitos?",""),
 (24,"Autosabotaje","l","¿Te autosaboteas? Si es así, ¿con qué actividad, hábito o pensamientos específicamente?","Autosabotaje es la tendencia de interrumpir tu progreso poniéndote obstáculos que impiden llegar a tu meta."),
 (25,"Estado emocional actual","l","¿Cómo te sientes ahora mismo en tu vida a nivel emocional?",""),
 (26,"Estado emocional deseado","l","¿Cómo te gustaría sentirte a nivel emocional?",""),
 (27,"Nivel de energía","r","¿Cómo te sientes a nivel de energía?","",["Muy poca energía, quiero quedarme acostado/a todo el día y me canso muy rápido","Poca energía, hago todas mis actividades pero me toma mucho esfuerzo","Suficiente energía como para rendir bien en todas mis actividades","Muchísima energía, quiero estar todo el día en movimiento"]),
 (28,"Metas","l","¿Cuáles son tus metas de aquí a un par de semanas, de aquí a un par de meses y de aquí a los siguientes años?",""),
 (29,"Mayor motivación","l","Cuál es tu mayor motivación para lograr estas metas? - Salud, relaciones, autoestima, superación, etc.","Especifica a detalle."),
 (30,"Cuerpo deseado","l","Cómo describirías al cuerpo que deseas?","Alguna característica o forma de denominarlo, por ejemplo: definido, tonificado, atlético, saludable, con abdomen definido, sin grasa del pectoral etc."),
 (31,"Intentos que sí funcionaron","l","¿Qué has intentado en el pasado que SI te ha funcionado?","Respecto a tu proceso de pérdida de grasa."),
 (32,"Buenos hábitos","l","¿Cuáles son tus buenos hábitos?",""),
 (33,"Referentes fitness","l","A quién sigues y quienes son tus referentes en el ámbito del fitness y bienestar físico?",""),
 (34,"Cómo coachearte","l","¿Cuál es la mejor manera de hacerte responsable/coachearte/asesorarte?","Todo el mundo quiere ser manejado/liderado/motivado de manera diferente. ¿Cómo podemos empujarte, guiarte y apoyarte mejor para hacer de esto un éxito masivo? Haremos todo lo posible para adaptar todo a tus necesidades."),
 (35,"Cómo descubriste a Lian","l","¿Dónde y cómo descubriste Lian?",'Sé específico, por ejemplo no pongas "Instagram" sino pon "Por instagram me apareció un video sobre no dejar el pan para bajar de peso, luego entré a su página web y me gustó su propuesta."'),
 (36,"Acciones antes de ingresar","c","Qué acciones tomaste antes de ingresar al Equipo HB?","Selecciona todas las opciones que correspondan.",["Vi un anuncio de Lian y el Equipo HB","Vi el perfil de instagram de Lian y el Equipo HB","Vi un par de videos o posts de Lian y el Equipo HB","Vi bastantes de videos o posts de Lian y el Equipo HB","Entré a su página web y vi su propuesta","Vi su masterclass gratuita","Conversé directamente con el por Instagram o Whatsapp","Me lo recomendó un conocido","Revisé los testimonios de los demás miembros"]),
 (37,"Conversación con tu entorno","l","¿Hablaste con alguien de tu entorno antes de ingresar? ¿Con quién? ¿Qué hablaste? ¿Como te ayudo/perjudico en la decisión?","Se específico."),
 (38,"Otras investigaciones","l","Qué otras investigaciones hiciste sobre el Equipo HB o Lian?",""),
 (39,"Tiempo en decidir","r","Cuánto tardaste en entrar al equipo HB desde que supiste de su existencia?","",["El mismo día que lo conocí","Dentro de los primeros días que lo conocí","En un par de semanas luego de haberlo conocido","Meses después de haberlo conocido","Años desde que lo conocí"]),
 (40,"Miedos y creencias previas","l","¿Qué miedos y creencias te limitaban antes de ingresar al programa? ¿Que te hizo romperlas?",""),
 (41,"Creencias sobre perder grasa","l","¿Qué miedos y creencias limitantes tenias respecto a perder peso y grasa?",""),
 (42,"Por qué ingresaste","l","¿Por qué ingresaste al equipo? ¿Qué fue lo que te convenció para ingresar?","Por favor detalla todo lo máximo posible."),
 (43,"Contenido que más impactó","l","¿Qué tipo de contenido/videos en redes sociales hecho por Lian son los que más impactaron en ti para tomar esta decisión?",""),
 (44,"Por qué confiaste","l","¿Porque confiaste en el Equipo HB?","Por favor detalla todo lo máximo posible."),
 (45,"Qué incluir en el programa","l","¿Qué te encantaría que incluyera o tratara este programa?",""),
 (46,"Qué no incluir","l","¿Qué NO quisieras que incluyera o tratara este programa?",""),
 (47,"Diferencia frente a competidores","l","¿Qué hace que veas al Equipo HB y a Lian diferente a otros competidores dentro del ámbito del bienestar físico y mental?","Diferencia frente a otros entrenadores, nutricionistas, etc."),
 (48,"Altura","s","Altura:",""),
 (49,"Peso","s","Peso corporal:","Si no tienes tu peso y no tienes como pesarte en estos momentos, escribe NT y luego me lo envías por Whatsapp cuando lo tengas."),
 (50,"Comidas del día","l","¿Cuántas comidas haces en el día? ¿Cómo son esas comidas? Detalla alimentos, cantidades y horario.","Si tienes un desorden, simplemente escribe los horarios que podrías hacer las comidas. Te dejo ejemplos de respuesta para responder correctamente.","q50"),
 (51,"Comidas que disfrutas","l","¿Qué comidas y alimentos disfrutas?",""),
 (52,"Comidas que desagradan","l","¿Qué comidas y alimentos te desagradan?",""),
 (53,"Momento de más hambre","l","En qué momento del día sientes más hambre?",""),
 (54,"Relación con la comida","l","Cómo es tu relación con la comida?","Prefieres comer algo simple y rápido sin problema en repetir o te gusta varias las comidas y probar recetas? Detalla por favor."),
 (55,"Frecuencia de dulces y chatarra","l","¿Cada cuánto comes dulces o comida chatarra?",""),
 (56,"Tabaco, alcohol o drogas","l","Fumas, bebes o consumes alguna droga? Si es así, cada cuanto y en cuánta cantidad?","Específica."),
 (57,"Agua al día","s","¿Cuánto agua tomas al día?",""),
 (58,"Actividad diaria","l","¿Cómo es tu actividad diaria? Sedentario o activo? - Detalla un día en tu vida con horarios y actividades.","Te dejo ejemplos para responder correctamente.","q58"),
 (59,"Antecedentes deportivos","l","¿Cuáles son tus antecedentes deportivos?","Entrenas o entrenabas, cómo eran esos entrenamientos, etc."),
 (60,"Dónde entrenar","l","Para el asesoramiento, donde preferirías entrenar? en gimnasio, casa o al aire libre?",""),
 (61,"Implementación disponible","l","Respecto a la pregunta anterior, ¿qué implementación tienes disponible?","Detalla lo que tengas en casa, en tu gym o en el parque donde piensas entrenar. Luego enviame una foto y/o video de esto por whatsapp."),
 (62,"Horarios diarios","l","¿Cómo son tus horarios en el día a día?","Rutina diaria, trabajo, hobbies, etc."),
 (63,"Productividad (1-10)","n","Del 1-10, qué tan productivo eres?","Organización, cumplimiento de tareas, etc."),
 (64,"Estrategias y apps","l","¿Aplicas estrategias o apps para llevar un registro de tareas y optimizar tu tiempo?",""),
 (65,"Días y horas para entrenar","s","¿Cuántos días y horas a la semana podrías entrenar?",""),
 (66,"Horas de sueño","r","¿Cuántas horas duermes diariamente?","",["Menos de 5 horas al día","Entre 5 - 6 horas al día","Entre 7 - 8 horas al día","Más de 8 horas por día"]),
 (67,"Calidad de sueño","r","¿Cómo es tu calidad de sueño? te despiertas en la noche o duermes profundo?","",["Duermo muy mal, despierto fácil y no me siento con energía","Duermo relativamente bien, a veces despierto pero no es seguido","Duermo muy bien, descanso buenas horas con un sueño profundo"]),
 (68,"Estrés (1-10)","n","Del 1-10, ¿qué tan estresado estás en tu día a día?","",["Muy relajado","Muy estresado, me irrito fácil"]),
 (69,"Manejo del estrés","l","¿Cómo manejas ese estrés? Específica",""),
 (70,"Lesiones u hormonales","l","Escribe tus antecedentes de lesiones o problemas hormonales","Tienes o has tenido, qué era específicamente, etc. Si no has tenido problemas, responde NT."),
 (71,"Mediciones corporales","l","Mediciones corporales.","Si no las tienes y no tienes como medirte en estos momentos, escribe NT y luego me lo envías por Whatsapp cuando lo tengas.","q71"),
 (72,None,"i","Por último, envíame a whatsapp 3 fotos de tu estado físico actual en esta posición.","Debe ser con peto y ropa deportiva o con ropa interior si eres mujer, si eres hombre debe ser con un short o con ropa interior. También envíame alguna foto con alguna prenda que te guste pero que al vestirla no te gusta como te queda, así también mediremos el progreso con la ropa.","q72"),
]
STEPS = [
 ("Sobre ti",[[1,2],[3],[4,5],[6,7],[8],[9],[10,11],[12],[13],[14,15],[16],[17],[18],[19,20],[21],[22,23],[24],[25,26],[27],[28],[29],[30],[31],[32,33],[34]]),
 ("Por qué ingresaste",[[35],[36],[37],[38,39],[40],[41],[42],[43],[44],[45,46],[47]]),
 ("Planificación",[[48,49],[50],[51,52],[53],[54],[55,56],[57],[58],[59],[60,61],[62],[63,64],[65],[66,67],[68,69],[70],[71],[72]]),
]
